apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: jikaheimo/ms-auth
      context: ms-auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: jikaheimo/ms-tickets
      context: ms-tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: jikaheimo/ms-orders
      context: ms-orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: jikaheimo/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "pages/**/*.vue"
            dest: .
          - src: "layouts/**/*.vue"
            dest: .
          - src: "components/**/*.vue"
            dest: .
          - src: "compositions/**/*.ts"
            dest: .
          - src: "api/**/*.ts"
            dest: .
