apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-auth
  template:
    metadata:
      labels:
        app: ms-auth
    spec:
      containers:
        - name: ms-auth
          image: jikaheimo/ms-auth
          envFrom:
            - secretRef:
                name: mysql-secret
          env:
            - name: MYSQL_HOST
              value: auth-mysql-srv
            - name: MYSQL_DB_NAME
              value: auth
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: ms-auth
  type: ClusterIP
  ports:
    - name: ms-auth
      protocol: TCP
      port: 3000
      targetPort: 3000
