apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mysql-depl
spec:
  selector:
    matchLabels:
      app: auth-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth-mysql
    spec:
      containers:
        - image: mariadb:latest
          name: auth-mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MARIADB_DATABASE
              value: test
          ports:
            - containerPort: 3306
              name: auth-mysql
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: auth-mysql-srv
  labels:
    name: auth-mysql
spec:
  selector:
    app: auth-mysql
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
